### PR TITLE
Improvements to the blueprints readme

### PR DESCRIPTION
**Pull request by margarethaley**
Made some changes to the blueprints readme page
- fixed minor typos
- rephrase the sentences to clarify their meaning
- added a heading, short summary, and links for continuous delivery page

Resolves https://github.com/operate-first/operate-first.github.io/issues/259

### CODE REVIEW

**Review by oindrillac — COMMENTED** [review]
/lgtm

**Comment by hemajv** [comment]
lgtm! :ship:

**Comment by oindrillac** [comment]
Is the pre-commit fail issue here related to the ongoing issues with prow https://github.com/operate-first/SRE/issues/347? 
cc: @harshad16 @HumairAK

**Comment by HumairAK** [comment]
@oindrillac probably, let's merge this for now, I ran the pre-commit locally, it ran fine

**Pull request merged**
