### PR TITLE
[WIP] Initial notes on user bucket access.

### PR DESCRIPTION
**Pull request by martinpovolny**

### CODE REVIEW

**Review by tumido — COMMENTED** [review]
@martinpovolny wanna have another look at this and adjust it to the current state of thigs, so we maybe can have it merged before today's meeting?

**Comment by martinpovolny** [comment]
@tumido , @HumairAK : something more along these lines? 
(see docs/userstories/request_a_storage_bucket.feature)

Thx for any feedback!

**Review by tumido — COMMENTED** [review]
yes the `.feature` file sounds looks much better to me. I think you can expand it on scenarios:
- "I don't have my openshift project -> Go to onboarding"
- "I don't know how to do it -> I issue this issue template"

if you rebase on top of recent changes from Humail, you may need to move the files around into the persona folder.

**Comment by tumido** [comment]
/unassing @tumido 

I think we may even want to close this one.. WDYT @HumairAK ?

**Pull request closed without merging**
