### PR TITLE
Add ci config files and run linting

### LINKED ISSUE #14: Add ci files to this repo and run linting
PR checks keep failing because the ci files do not exist in this repo, and all markdown files are not properly linted due to this.

### PR DESCRIPTION
**Pull request by HumairAK**
Fixes #14

### CODE REVIEW

**Comment by HumairAK** [comment]
Ignore the build-check test failing, this should be resolved after the pr is merged.

**Review by 4n4nd — APPROVED** [review]
LGTM :+1:

**Review by hemajv — APPROVED** [review]
:ship:

**Pull request merged**
